server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册金Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/quicktolearn/springcloud-config.git
          ####搜索目录
          search-paths:
            - springcloud-config
      label: main



eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka